apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-claim-serve-deployment
  labels:
    app: health-claim-serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-claim-serve
  template:
    metadata:
      labels:
        app: health-claim-serve
    spec:
      containers:
      - name: health-claim-serve
        image: health-claim-serve:v1
        ports:
        - containerPort: 8000  # Port for FastAPI
        - containerPort: 7863  # Port for Gradio
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "500m"
